help:
  channel : "Olá, irei passar uma lista de comandos para você !"
  lain    : "~lain  : Bem... precisamos saber se o Lain é otaku, né ?"
  jap     : "~jap   : Todo dia é dia de entender o que cada kanji significa !"
  chuni   : "~chuni : Vamos iniciar uma nova aventura juntos ?!"
  motivar : "~motiva: Uma boa motivação para o seu dia de luta !"
  ajuda   : "~ajuda : Envio de lista de comandos no privado."
